[project]
name = "FLPP"
version = "1.3.0"
description = 'FLPP is a simple lua-python data structures parser for Blackmagic Fusion'
readme = "README.md"
requires-python = ">=3.7"
authors = [{ name = "SirAnthony" }, { name = 'Alexey Bogomolov' }]
